language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pytest
  - pip install coveralls pytest-cov pytest
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov plateo --cov-report term-missing

after_success:
  - coveralls
