language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install --upgrade pytest coveralls pytest-cov
install:
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov plateo --cov-report term-missing

after_success:
  - coveralls
